---
apiVersion: v1
kind: Secret
metadata:
  name: devhub-orders-backend-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/devhub-backend-gitops